[project]
name = "taleweaver"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "yashaswigarg", email = "yashaswigarg0506@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "langchain>=1.4.0",
    "langchain-google-genai>=4.4.0",
    "langgraph>=1.2.11",
    "langgraph-checkpoint-sqlite>=3.1.1",
    "mcp>=2.2.0",
    "pydantic>=2.13.5",
    "python-dotenv>=1.2.3",
    "rich>=15.0.0",
]


[project.scripts]
taleweaver = "taleweaver:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
