"""State models and Pydantic schemas for TaleWeaver's LangGraph engine."""

from __future__ import annotations

from typing import List, Literal, Optional
from typing_extensions import TypedDict
from pydantic import BaseModel, Field


class CharacterRole(str):
    PROTAGONIST = "protagonist"
    COMPANION = "companion"
    ANTAGONIST = "antagonist"
    MENTOR = "mentor"
    SUPPORTING = "supporting"


class CharacterProfile(BaseModel):
    """Detailed profile for a story character."""

    name: str = Field(description="Character's full or alias name")
    role: Literal["protagonist", "companion", "antagonist", "mentor", "supporting"] = Field(
        description="Dramatic role of the character"
    )
    archetype: str = Field(description="Character class, profession, or archetype")
    traits: List[str] = Field(default_factory=list, description="Key personality or physical traits")
    backstory: str = Field(description="Brief, compelling backstory or secret")
    inventory: List[str] = Field(default_factory=list, description="Signature items or starting equipment")
    status: str = Field(default="Healthy and ready", description="Current physical / emotional status")


class WorldLore(BaseModel):
    """The foundational setting and narrative rules for the story."""

    title: str = Field(description="The chosen or enhanced story title")
    genre: str = Field(description="Primary and secondary genre blend")
    storyline: Optional[str] = Field(
        default="", description="User-provided custom storyline, premise, or narrative trajectory"
    )
    setting_description: str = Field(description="Atmospheric description of the world/locations")
    magic_or_tech_rules: str = Field(description="Key laws of physics, magic, or society/technology")
    primary_conflict: str = Field(description="Overarching stakes or looming threat/goal")
    tone: str = Field(description="Narrative tone (e.g. Comedic, Whimsical, Gritty, Noir, Cosmic Mystery)")


class StoryChoice(BaseModel):
    """A branching decision offered to the player at chapter's end."""

    id: int = Field(description="Choice number (e.g. 1, 2, 3)")
    text: str = Field(description="Action the protagonist takes")
    consequence_hint: Optional[str] = Field(
        default=None, description="Subtle teaser of potential risk or reward"
    )


class InventoryEvent(BaseModel):
    """An item gained or consumed during chapter narrative."""

    character_name: str = Field(description="Name of the character")
    item: str = Field(description="Item name")
    action: Literal["add", "remove"] = Field(description="Whether item was added or removed")


class ChapterDraft(BaseModel):
    """Raw narrative draft generated by the Scribe agent."""

    chapter_number: int = Field(description="Sequential chapter number")
    title: str = Field(description="Evocative chapter title")
    content: str = Field(description="The prose narrative of the chapter")
    cliffhanger: str = Field(description="The unresolved tension, revelation, or decision point at the end")
    is_finale: bool = Field(default=False, description="True if this is the final resolution chapter")
    inventory_events: List[InventoryEvent] = Field(
        default_factory=list, description="Items acquired or used by characters in this chapter"
    )
    choices: List[StoryChoice] = Field(
        default_factory=list, description="3 divergent paths forward (empty if is_finale=True)"
    )


class EditorCritique(BaseModel):
    """Quality control evaluation from the Grand Arbiter agent."""

    approved: bool = Field(description="True if quality, tone, and pacing meet standards")
    score: int = Field(description="Rating from 1 to 10")
    critique: str = Field(description="Specific, actionable feedback or praise")
    required_fixes: List[str] = Field(
        default_factory=list, description="Bullet points for the Scribe to fix"
    )


class IllustrationPrompt(BaseModel):
    """Detailed visual description created by the Art Director agent."""

    chapter_number: int = Field(description="Associated chapter number")
    scene_title: str = Field(description="Key dramatic scene depicted")
    visual_prompt: str = Field(
        description="High-detail prompt specifying lighting, composition, mood, and subjects"
    )
    art_style: str = Field(
        default="Cinematic Concept Art, vibrant palette, atmospheric lighting",
        description="Recommended artistic medium/style",
    )


class ChapterRecord(BaseModel):
    """Permanent finalized record of a completed chapter."""

    chapter_number: int
    title: str
    content: str
    visual_prompt: str
    chosen_action: Optional[str] = None
    is_finale: bool = False


class StoryState(TypedDict, total=False):
    """Comprehensive state dictionary managed by the LangGraph orchestrator."""

    # Game Premise & User Guidance
    title: str
    genre: str
    storyline: Optional[str]
    target_chapters: int
    world_lore: Optional[WorldLore]
    world_approved: bool

    # Character Roster & HitL Approval
    characters: List[CharacterProfile]
    characters_approved: bool
    character_feedback: Optional[str]

    # Narrative Progression
    current_chapter_num: int
    rolling_summary: str
    active_draft: Optional[ChapterDraft]
    editor_critique: Optional[EditorCritique]
    revision_count: int

    # Art & Publishing
    current_illustration: Optional[IllustrationPrompt]
    published_chapters: List[ChapterRecord]

    # Player Interaction (HitL)
    player_decision: Optional[str]
    game_over: bool
    status_message: str
